apiVersion: skaffold/v4beta1
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
build:
  local:
    push: false
  artifacts:
    - image: akbar010202/auth
      context: auth
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: akbar010202/posts
      context: posts
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: akbar010202/review
      context: reviews
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: akbar010202/client
      context: client
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
